Disable vdf eth call and estimate gas
EZChain-core/ezchain-coreth pull request #23
Opened 2022-04-10 02:35 UTC by diepmv

2022-04-10 07:49 UTC, Zergity requested changes

2022-04-10 07:49 UTC, Zergity commented on core/vm/evm.go
> +		if evm.Config.DisableVDF && addr == common.BytesToAddress([]byte{0xF1}) {
the `DisableVDF` flag must be used in `func (w *wrappedPrecompiledContract) Run(`, where the `w.p` is check with `vdfVerify` (using type assertion), then it can call another version of `func (c *vdfVerify) Run(input []byte, skipCalculation bool)`. This version of `Run` will have only this line skipped `ok := vdf_go.VerifyVDF(seed, output, int(iteration), int(bitSize))`.

2022-04-11 01:04 UTC, Zergity submitted a review, later dismissed
`delegateVdf` contract should be something like this, and the test can call `deleteVdf.verify` just like the original `vdf.verify`. Note: using the vdf ABI for delegateVdf contract constructor
```
delegateVdf = await deploy(`
    /**
     * @dev fallback implementation.
     * Extracted to enable manual triggering.
     */
    fallback() external payable {
        _delegate(${vdf.address});
    }

    /**
     * @dev Delegates execution to an implementation contract.
     * This is a low level function that doesn't return to its internal call site.
     * It will return to the external caller whatever the implementation returns.
     * @param implementation Address to delegate.
     */
    function _delegate(address implementation) internal {
        assembly {
            // Copy msg.data. We take full control of memory in this inline assembly
            // block because it will not return to Solidity code. We overwrite the
            // Solidity scratch pad at memory position 0.
            calldatacopy(0, 0, calldatasize())

            // Call the implementation.
            // out and outsize are 0 because we don't know the size yet.
            let result := delegatecall(gas(), implementation, 0, calldatasize(), 0, 0)

            let size := returndatasize()
            // Copy the returned data.
            returndatacopy(0, 0, size)

            switch result
            // delegatecall returns 0 on error.
            case 0 { revert(0, size) }
            default { return(0, size) }
        }
    }
`, wallet)
```

2022-04-13 05:00 UTC, Zergity requested changes

2022-04-13 05:00 UTC, Zergity commented on core/vm/contracts_stateful.go
> +	if evm.Config.DisableVDF && ok {
please don't duplicate code, pass the config down to the lower-most layer
```
func RunPrecompiledContract(p PrecompiledContract, input []byte, suppliedGas uint64) (ret []byte, remainingGas uint64, err error) {
	return RunPrecompiledContractWithConfig(p, input, suppliedGas, nil)
}

func RunPrecompiledContractWithConfig(p PrecompiledContract, input []byte, suppliedGas uint64, config *vm.Config) (output []byte, remainingGas uint64, err error) {
	gasCost := p.RequiredGas(input)
	if suppliedGas < gasCost {
		return nil, 0, ErrOutOfGas
	}
	suppliedGas -= gasCost
	vdf, ok := p.(*vdfVerify)
	if ok && config != nil && config.DisableVDF {
		output, err = vdf.run(input, true)
	} else {
		output, err = p.Run(input)
	}
	return output, suppliedGas, err
}
```

2022-04-13 13:45 UTC, diepmv commented on core/vm/contracts_stateful.go
> +	if evm.Config.DisableVDF && ok {
I fixed this, thanks

2022-04-13 16:02 UTC, merged