Sponsor tx
EZChain-core/ezchain-coreth pull request #32
Opened 2022-04-28 21:40 UTC by diepmv

2022-04-29 12:25 UTC, Zergity requested changes

2022-04-29 12:25 UTC, Zergity commented on core/state_transition.go
> +		sponsorTx, err := st.decodeSponsorTx()
just call `decodeSponsorTx` inside `decodeFeePayer` to make this part more clean

2022-05-01 01:25 UTC, diepmv commented on core/state_transition.go
> +		sponsorTx, err := st.decodeSponsorTx()
@Zergity I've pushed a new commit to fix this

2022-05-02 04:55 UTC, Zergity approved these changes
1 minor refactor and it's good

2022-05-02 04:55 UTC, Zergity commented on core/state_transition.go
> -
please remove unnecessary white-space change

2022-05-02 04:58 UTC, merged